#!/usr/bin/env bash
# Guard against accidental writes to sensitive or immutable files.
# Exit 2 = block the action and feed stderr back to Claude.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
[[ -z "$FILE_PATH" ]] && exit 0

# Block writes to environment files (secrets must be managed manually)
if [[ "$FILE_PATH" =~ (^|/)\.env($|\.) ]]; then
	echo "Blocked: Refusing to write to environment file '${FILE_PATH}'." >&2
	echo "Environment files contain secrets and must be edited manually." >&2
	exit 2
fi

# Block direct edits to migration SQL files (use bun db:generate instead)
if [[ "$FILE_PATH" =~ /drizzle/.*\.(sql|meta)$ ]]; then
	echo "Blocked: Do not edit migration files directly: '${FILE_PATH}'." >&2
	echo "Run 'bun db:generate' to create new migrations from schema changes." >&2
	exit 2
fi

# Block edits to auto-generated route tree
if [[ "$FILE_PATH" =~ routeTree\.gen\.ts$ ]]; then
	echo "Blocked: Do not edit routeTree.gen.ts — it is auto-generated by TanStack Router." >&2
	exit 2
fi

exit 0
